name: Build and push to ECR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{  secrets.AWS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{  secrets.AWS_SECRET_ACCESS_KEY  }}
          aws-region: ap-south-1
        
      - name: Login to ECR
        run: |
            aws ecr get-login-password --region ap-south-1 \
              | docker login --username AWS --password-stdin 058227731591.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        run: |
            docker build -t 058227731591.dkr.ecr.ap-south-1.amazonaws.com/prayer-requests-wall:${{ github.sha }} .

      - name: Push image to ECR
        run: |
            docker push 058227731591.dkr.ecr.ap-south-1.amazonaws.com/prayer-requests-wall:${{ github.sha }}
