substitutions:
  _ARTIFACT_REGION: "asia-south1"
  _REPOSITORY: "prayer-repository"
  _IMAGE_NAME: "prayer-wall-app"
  _VM_NAME: "project-intercessor"
  _VM_ZONE: "asia-south1-c"

steps:
  # 1. Build the container image with Commit SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_ARTIFACT_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'
      - '-t'
      - '${_ARTIFACT_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:latest'
      - '.'

  # 2. Push the container image (both tags)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_ARTIFACT_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_ARTIFACT_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:latest'



  # ---------------------------------------
  # Execute deployment
  # ---------------------------------------
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'run-deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail

        # Define the image path (using built-in project ID variable)
        IMAGE="${_ARTIFACT_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA"

        echo "Deploying image: $$IMAGE"

        # Execute the deployment script on the VM
        # Note: We escape $$IMAGE so the shell sees the variable value, not Cloud Build substitution
        gcloud compute ssh ${_VM_NAME} \
          --zone=${_VM_ZONE} \
          --command "export DEPLOY_IMAGE='$$IMAGE' && \
                     export HOST_DATA_PATH='/var/intercessor/data' && \
                     /opt/deploy/deploy-docker.sh"
images:
  - '${_ARTIFACT_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA'
  - '${_ARTIFACT_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
